name: TuTienPlugin
version: '${project.version}'
main: com.yourname.tutien.TuTienPlugin
api-version: '1.21'
author: YourName
description: Plugin Tu Tiên với hệ thống tu luyện toàn diện.

commands:
  tutien:
    description: Lệnh chính của plugin Tu Tiên.
    usage: /<command> [info|truyenlinhkhi]
    aliases: [tt, tuchan]
  tuluyen:
    description: Bắt đầu hoặc kết thúc trạng thái tu luyện (thiền định).
    usage: /<command>
    aliases: [tl, thien]
  dotpha:
    description: Bắt đầu quá trình đột phá đại cảnh giới khi đã đủ điều kiện.
    usage: /<command>
  setlinhkhi: # <-- THÊM KHỐI LỆNH MỚI
    description: (Admin) Đặt một lượng linh khí cụ thể cho bản thân.
    usage: /<command> <số_lượng>
    permission: tutien.admin # Chỉ người có quyền này mới dùng được
