name: Build TuTienPlugin

# Trigger: Chạy workflow này mỗi khi có ai đó push code lên nhánh "main"
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Chạy trên một máy ảo Ubuntu phiên bản mới nhất
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Tải mã nguồn của bạn về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Java Development Kit (JDK) phiên bản 17
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # Sử dụng bản phân phối Temurin (Eclipse Adoptium)
          cache: 'maven' # Cache các file Maven để build nhanh hơn ở các lần sau

      # Bước 3: Build dự án bằng Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Bước 4: Tải lên thành phẩm (artifact)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Tên của artifact sẽ được hiển thị trên GitHub
          name: TuTienPlugin-JAR
          # Đường dẫn đến file cần tải lên
          # **/*.jar sẽ tìm bất kỳ file .jar nào trong thư mục target
          path: target/*.jar
